export const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
export const GET_JOBS_FAILURE = "GET_JOBS_FAILURE";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

export const FILTER_JOBS = "FILTER_JOBS";
export const LOCATION_CHANGE = "@@router/LOCATION_CHANGE";

export const JOIN_SLACK_REQUEST = "JOIN_SLACK_REQUEST";
export const JOIN_SLACK_FAILURE = "JOIN_SLACK_FAILURE";
export const JOIN_SLACK_SUCCESS = "JOIN_SLACK_SUCCESS";
